### ISSUE TITLE
timeout on MQTTClient_waitfor()

### ISSUE THREAD

**Issue by AcoemDlu** [eclipse/paho.mqtt.m2mqtt#12]
Paho C MQTT APIs compiled with VisualStudio 2015 
I want to send message to IoT Hub.
I have a timeout on Thread_wait_sem()
I use this configuration:
"DeviceAcoem"
  , "\n"
  , 100
  , 0
  , 0
  , "xxx.azure-devices.net/DeviceAcoem"
  , "SharedAccessSignature sr=xxx.azure-devices.net%2fdevices%2fDeviceAcoem&sig=3DO9XHIa0igyCYdYp%2bTd2VwPkROxiRvEAIQK3X9Uqg4%3d&se=1501234285"
  , "xxx.azure-devices.net"
  , "1883"
  , 1

Thanks for your reply

**Comment by ppatierno** [comment]
I think you posted the question on the wrong project. This is the C# / .Net implementation.
