### ISSUE TITLE
Not detect when disconnect

### ISSUE THREAD

**Issue by serkanayaz** [eclipse/paho.mqtt.m2mqtt#65]
Hi,

Library is not detect when disconnect.

Scenario: Library is connect to any mqtt server and internet is disconnect (or disable wifi). Now, Should be run Mqtt_ConnectionClosed event but not run.

Best regard.

**Comment by serkanayaz** [comment]
Sorry, it is detect when disconnected, but after long time.

**Comment by Salma175** [comment]
close this issue

**Comment by serkanayaz** [comment]
I need a mechanism where I can set the KeepAlive field. Or how can I set the KeepAlive field?

**Comment by Salma175** [comment]
client.Connect(client_id, userName, password, false, 3)
Last parameter is KeppAlive Period

**Comment by serkanayaz** [comment]
Thank you very much @Salma175 . It works correctly by setting X time short.
